### ISSUE TITLE
Las's checklist of KT functionality

### ISSUE THREAD

**Issue by alphalas** [BSData/wh40k-7th-edition#3037]
- [x] Adepta Sororitas
- [x] Astra Militarum
- [x] Armoured Battle Group	
- [x] Death Korp of Krieg Assault Brigade	
- [x] Death Korp of Krieg Siege Regiment	
- [x] Elysian Detachment D-99	
- [x] Elysian	
- [x] Grey Knights
- [x] Inquisition
- [x] Legion of the Damned	
- [x] Militarum Tempestus

**Comment by alphalas** [comment]
related to #2535
