### ISSUE TITLE
8th Ed Cat file Update Tracking

### ISSUE THREAD

**Issue by tag8833** [BSData/wh40k-7th-edition#3737]
## **Edit:  This thread is getting crowded.  Please post any error reports ~~in issues referenced beside appropriate catalogue, or if none is given,~~ as seperate issues using the "New Issue" button.**  

We've got a number of people popping in that want to help us validate data files.  Let's put them to work by letting them know which data files are ready for validation. 

If you want to help validate files, you can find them here:
https://github.com/BSData/wh40k/tree/40k8eprep

Make sure you are updated to BS version 2.01
*Edit: BS 2.01 is production now, so just update.

Ready For Validation:
- [x] Adeptus Astra Telepathica
- [x] Adeptus Custodes
- [x] Adeptus Mechanicus
- [x] Astra Militarum
- [x] Adeptus Ministorum #3854
- [x] Blood Angels #3820
- [x] Chaos Daemons #3766
- [x] Chaos Space Marines #3766
- [x] Craftworlds
- [x] Death Guard #3766
- [x] Dark Angels
- [x] Deathwatch
- [x] Drukhari
- [x] Genestealer Cults
- [x] Grey Knights
- [x] Harlequins #3803
- [x] Imperial Knights (Questor Imperialis)
- [x] Inquisition
- [x] Legion of the Damned
- [x] Necrons
- [x] Officio Assassinorum
- [x] Orks
- [x] Renegade Knights (Questor Traitoris) #3766
- [X] Sisters of Silence
- [x] Space Marines #3797
- [x] Space Wolves #3837
- [x] Tau
- [x] Thousand Sons #3766
- [x] Tyranids
- [x] Unaligned (Fortifications)
- [ ] Ynnari

Post a little update if you've validated one of the files, and it looks good.   That way we know which ones aren't getting attention.

**Comment by tag8833** [comment]
I did a pass validating: 
Adeptus Astra Telepathica
Adeptus Custodes
Officio Assassinorum
Sisters of Silence
Genestealer Cult

**Comment by ghost** [comment]
Tau is ready to be validated but needs a serious syntax and style check. Lots of stuff I feel I did badly and could use some pointers.

**Comment by DrTobogganMD** [comment]
Necrons ready to be validated :)

**Comment by M4uler** [comment]
Checking Tyranids, the units seem fine.  Regarding the Wounds vs Stats tables I'd suggest that they should be added in as Profile Types locally, one per table type.  eg one is [Ws, S & A], another is [Ws, WS, S & A], [Ws, BS, S & A], etc.

Updated my CAT, attaching for use/reference.  :]



[Tyranids.txt](https://github.com/BSData/wh40k/files/1052475/Tyranids.txt)

**Comment by Pacemaker59** [comment]
Necron Destroyers should be able to take 6 Destroyers or 5 Destroyers and 1 Heavy.  Currently it says the max selections of destroyer is 4 if you take a heavy and won't let you go above 5 if you don't.

This is the only bug I've seen going through the Necron list.

Thanks for working on this!

**Comment by DrTobogganMD** [comment]
@Pacemaker59 Fixed.

**Comment by cartag** [comment]
Daemons and Questor Traitoris ready for testing

**Comment by Crowbar90** [comment]
Legion of the Damned is ready for testing as well.

**Comment by Subdual** [comment]
Necron Triarch Stalker's particle shredder type says "heavy" when it should say "heavy 6"
Right now you can't have more than 10 flayed ones. They should have maximum unit size of 20.
I have encountered these errors while building a patrol detachment if that has any relevance.

**Comment by Mik-l** [comment]
I have been going through the Drukhari list on Battlescribe, but I am unfamilliar with Github. How should report errors/validations, should I just post them in this comment section or is there somewhere else?

Thank you for all your work so far!

**Comment by ninchistudios** [comment]
@cartag for Questor Traitoris:

- 0 Titanic Feet should not be a valid option.
- (None) Ranged Weapon should not be a valid option.
- Selecting a Knight Weapon in place of the Reaper Chainsword invalidates every selection for Thunderstrike Gauntlet and options including the default Thunderstrike Gauntlet (and vice versa). RAW you should be able to replace either or both of your default arm weapons with a Knight Weapon.
- Is there a way to show the reducing characteristics with damage on the roster?
- Knight Weapon "Avenger Gatling Cannon and Heavy Flamer" should be 112pts
- Knight Weapon "Rapid-fire Battle Cannon and Heavy Stubber" should be 104pts.
Otherwise grand, thanks for your work.

**Comment by cartag** [comment]
@miproductions have all but the knight weapon invalidation working, will be uploaded later.

**Comment by M4uler** [comment]
Tyranids - Hive Tyrant Monstrous Talons need a rework; they're 20.5pts each in the .cat which is fine if you take two pairs at 41pts, but a single pair is 31pts, not 20.5.

Otherwise that and the tables above, lookin' pretty legit :]

**Comment by GenWilhelm** [comment]
@M4uler, they change cost depending on how many you take.

**Comment by tag8833** [comment]
@Mik-l You can add comments here, or open a new issue for them.  If you've got alot of feedback, probably open a new issue, that way you and the data file author can go back and forward a bit if he's got questions about your feedback.

**Comment by M4uler** [comment]
@GenWilhelm Aye, I saw after posting and deleted - nice work :D

Considering adding the wound tables from the file I uploaded?  I'm happy to do them for each codex so rosters are more descriptive.

**Comment by GenWilhelm** [comment]
@M4uler, we talked about it briefly on Gitter, but there was no general consensus on whether or not to make it a standard. You're welcome to come and discuss it with us if you want to do it across all catalogues.

**Comment by M4uler** [comment]
@GenWilhelm Rgr that, I'll see if I can find the time.  If I'm gonna properly do it for all catalogues it might be better for each table type to be added into the game system file and the cats just link to those...

**Comment by GenWilhelm** [comment]
@M4uler that was one of the points that was brought up, best solution is probably to have the most common ones in the GST, and more specific ones in CATs.

Again, the best place to discuss this is on Gitter, rather than a file validation thread.
https://gitter.im/BSData/wh40k

**Comment by M4uler** [comment]
@Bitjump Added descriptive wound tables to the Tau file along with a Markerlight table.  Validation to follow :]
[Tau Empire.txt](https://github.com/BSData/wh40k/files/1055637/Tau.Empire.txt)

**Comment by Crowbar90** [comment]
I finished data entry for Blood Angels so it's ready for testing.

**Comment by Jasqes** [comment]
Orks - Runtherd unit should not be able to take multiple runtherds. Also a Runtherd shouldn't be able to take both a squig hound and a grot lash, it's either/or
Ork boyz are S4 not S5.
Deff dread - the points cost is ok, but in preview it says that 2x Dread Klaw is 30p, while it should be 45.

**Comment by Jasqes** [comment]
I've made a patrol list for Orks and came across the following issues:
Runtherd unit should not be able to take multiple runtherds. Also a Runtherd shouldn't be able to take both a squig hound and a grot lash, it's either/or
Ork boyz are S4 not S5.
Deff dread - the points cost is ok, but in preview it says that 2x Dread Klaw is 30p, while it should be 45.
Also the Mob Rule and 'Ere we go rule references do not point to specific page in Xenos 2 book (pg 10)

**Comment by mdmagnusson** [comment]
@Crowbar90 The Flamerstorm Cannon for the the Landraider Redeemer and the one in the Space Marine Wargear is listed as "Heavy 6" but the one in the Baal Predator profile is listed as "Assault 6". However the Data entry for Baal Predator uses the "Heavy 6" profile.

**Comment by tag8833** [comment]
@Jasqes Check the points list.  It allows units of runtherds.    There is a similar issue with Deffkoptas.  In the Datasheet they are 1-5, in the points list they are 1-3.  I went with the points list to resolve conflicts.  I figure the path of least resistance going forward is to go with the least restrictive number, so I expanded Deff Koptas to 1-5.   It's a clear typo.  Just not sure how to resolve it exactly.

Runtherd is fixed.

Ork Boyz are fixed.  

Page Reference is added. 

For the Deff Dread, the Pair of Klaw arms is right, it was just confusing.  I've Renamed it to make it clearer.  

Thanks for the feedback.

**Comment by Examinus88** [comment]
For Blood Angels the tactical squad entry is not working properly. Units can be added to the list but adding extra marines adds them to every tactical squad in the roster. Also after adding a marine and then adding another squad the entry freezes and cant be removed or added.

edit: clarification of problem.

**Comment by Toreador13** [comment]
@Mik-i it is probably easier as an issue, especially if you have multiple bugs.

**Comment by cartag** [comment]
@miproductions can you check Questor Traitoris again when you get the chance?

**Comment by ghost** [comment]
Runtherds have the <CHARACTER> keyword, so they should be a single-model unit. I'd say "1-3" in the point list is an error so the easiest resolution is to leave Runtherds as a single model.

The text in the dataslate is pretty conclusive too - "a Runtherd is a single model"...

Have validated and posted a list of issues with the v1 Orks file separately (see the commit for that file https://github.com/BSData/wh40k/commit/5fae90ec67c2e743cdd2016ddb81a0b3256951f1?diff=unified).

**Comment by FarseerVeraenthis** [comment]
Craftworlds CAT is done.

**Comment by penguin20000** [comment]
Space Wolves version 1 ready for checking :)

I'm sure there's quite a bit of optimising to do as this is the first major cat I've worked on. The major focus was getting all the data in to start with.

**Comment by tag8833** [comment]
Inquisition is Done.

**Comment by amis92** [comment]
We're down to having only 3 left to do:

* Astra Militarum - @alphalas 
* Space Marines - @flakpanda 
* Ynnari - @USSX-Hares (is that still correct?)

I plan to freeze repo tomorrow evening and do the #3721 - how are you guys on schedule? Remember, if time is short, leave rules and profiles - these are lowest priority. Most important is ability to select units and calculate points correctly (even PLs are lower priority).

**Comment by amis92** [comment]
Done. New repo: https://github.com/BSData/wh40k
